//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists
    {
        public Artists()
        {
            this.Playlists = new HashSet<Playlists>();
            this.SangSongs = new HashSet<Songs>();
            this.WroteSongs = new HashSet<Songs>();
            this.LikedUsers = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RealName { get; set; }
        public string CompanyName { get; set; }
        public string Image { get; set; }
        public string Info { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Website { get; set; }
        public int View { get; set; }
    
        public virtual Countries Country { get; set; }
        public virtual ICollection<Playlists> Playlists { get; set; }
        public virtual ICollection<Songs> SangSongs { get; set; }
        public virtual ICollection<Songs> WroteSongs { get; set; }
        public virtual ICollection<UserProfile> LikedUsers { get; set; }
    }
}
