//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistComment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PlaylistId { get; set; }
        public string Content { get; set; }
        public System.DateTime PostTime { get; set; }
    
        public virtual UserProfile User { get; set; }
        public virtual Playlists Playlists { get; set; }
    }
}
