//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlists
    {
        public Playlists()
        {
            this.Comments = new HashSet<PlaylistComment>();
            this.SongsInPlaylist = new HashSet<SongPlaylist>();
            this.LikedUsers = new HashSet<UserProfile>();
            this.Categories = new HashSet<Categories>();
            this.Artists = new HashSet<Artists>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int View { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> StaffPickedTime { get; set; }
    
        public virtual ICollection<PlaylistComment> Comments { get; set; }
        public virtual UserProfile User { get; set; }
        public virtual ICollection<SongPlaylist> SongsInPlaylist { get; set; }
        public virtual ICollection<UserProfile> LikedUsers { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Artists> Artists { get; set; }
    }
}
