//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public Songs()
        {
            this.Comments = new HashSet<SongComment>();
            this.Categories = new HashSet<Categories>();
            this.LikedUsers = new HashSet<UserProfile>();
            this.SongPlaylist = new HashSet<SongPlaylist>();
            this.Singers = new HashSet<Artists>();
            this.Writers = new HashSet<Artists>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string MusicFile { get; set; }
        public string VideoFile { get; set; }
        public string Image { get; set; }
        public string Quality { get; set; }
        public int View { get; set; }
        public int Download { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> StaffPickedTime { get; set; }
        public string Lyrics { get; set; }
    
        public virtual Countries Country { get; set; }
        public virtual ICollection<SongComment> Comments { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<UserProfile> LikedUsers { get; set; }
        public virtual ICollection<SongPlaylist> SongPlaylist { get; set; }
        public virtual ICollection<Artists> Singers { get; set; }
        public virtual ICollection<Artists> Writers { get; set; }
    }
}
