//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongPlaylist
    {
        public int SongId { get; set; }
        public int PlaylistId { get; set; }
        public int Order { get; set; }
    
        public virtual Playlists Playlist { get; set; }
        public virtual Songs SongInfo { get; set; }
    }
}
