//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.CommentedPlaylists = new HashSet<PlaylistComment>();
            this.CommentedSongs = new HashSet<SongComment>();
            this.LikedSongs = new HashSet<Songs>();
            this.Roles = new HashSet<webpages_Roles>();
            this.Playlists = new HashSet<Playlists>();
            this.LikedPlaylists = new HashSet<Playlists>();
            this.LikedArtists = new HashSet<Artists>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<PlaylistComment> CommentedPlaylists { get; set; }
        public virtual ICollection<SongComment> CommentedSongs { get; set; }
        public virtual ICollection<Songs> LikedSongs { get; set; }
        public virtual ICollection<webpages_Roles> Roles { get; set; }
        public virtual ICollection<Playlists> Playlists { get; set; }
        public virtual ICollection<Playlists> LikedPlaylists { get; set; }
        public virtual ICollection<Artists> LikedArtists { get; set; }
    }
}
